In [ ]:
import numpy as numpy
import pandas as panda
from mlxtend.frequent_patterns import apriori, association_rules
from mlxtend.preprocessing import TransactionEncoder

In [19]:
ds = panda.read_csv("bread basket.csv") #membaca file csv
ds.head() #menampilkan data teratas

   Transaction           Item         date_time period_day weekday_weekend
0            1          Bread  30-10-2016 09:58    morning         weekend
1            2   Scandinavian  30-10-2016 10:05    morning         weekend
2            2   Scandinavian  30-10-2016 10:05    morning         weekend
3            3  Hot chocolate  30-10-2016 10:07    morning         weekend
4            3            Jam  30-10-2016 10:07    morning         weekend

In [ ]:
ds=ds.drop(ds.loc[ds['Item']=='NONE'].index) #menghapus kolom Item pada index yang bernilai None 
ds.groupby('period_day')['Item'].count().sort_values(ascending=False) #mengurutkan jumlah banyaknya transaksi yang terjadi pada tabel period_day

period_day
afternoon    11569
morning       8404
evening        520
night           14
Name: Item, dtype: int64

In [ ]:
lst=[]
for item in ds['Transaction'].unique():
    lst2=list(set(ds[ds['Transaction']==item]['Item']))
    if len(lst2)>0:
        lst.append(lst2)
print(lst[0:3])
print(len(lst))

[['Bread'], ['Scandinavian'], ['Jam', 'Cookies', 'Hot chocolate']]
9465

In [ ]:
te=TransactionEncoder()
te_data=te.fit(lst).transform(lst)
data_x=panda.DataFrame(te_data,columns=te.columns_)
data_x.head()

   Adjustment  Afternoon with the baker  ...  Vegan mincepie  Victorian Sponge
0       False                     False  ...           False             False
1       False                     False  ...           False             False
2       False                     False  ...           False             False
3       False                     False  ...           False             False
4       False                     False  ...           False             False

[5 rows x 94 columns]

In [ ]:
#Algoritma Apriori
frequent_items= apriori(data_x, use_colnames=True, min_support=0.03)
print(frequent_items.head())

rules = association_rules(frequent_items, metric="lift", min_threshold=1)
rules.antecedents = rules.antecedents.apply(lambda x: next(iter(x)))
rules.consequents = rules.consequents.apply(lambda x: next(iter(x)))
rules

    support     itemsets
0  0.036344  (Alfajores)
1  0.327205      (Bread)
2  0.040042    (Brownie)
3  0.103856       (Cake)
4  0.478394     (Coffee)

  antecedents consequents  antecedent support  ...      lift  leverage  conviction
0        Cake      Coffee            0.103856  ...  1.101515  0.005044    1.102664
1      Coffee        Cake            0.478394  ...  1.101515  0.005044    1.011905
2   Medialuna      Coffee            0.061807  ...  1.189878  0.005614    1.210871
3      Coffee   Medialuna            0.478394  ...  1.189878  0.005614    1.012667
4      Coffee      Pastry            0.478394  ...  1.154168  0.006351    1.014740
5      Pastry      Coffee            0.086107  ...  1.154168  0.006351    1.164682
6    Sandwich      Coffee            0.071844  ...  1.112792  0.003877    1.115384
7      Coffee    Sandwich            0.478394  ...  1.112792  0.003877    1.008807

[8 rows x 9 columns]